version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
        
      - run: mvn verify
        
      - run:
          name: Code Coverage
          command: bash <(curl -s https://codecov.io/bash)
